package com.demo.entity;

import com.demo.enums.DeckType;
import com.demo.enums.LayoutArrangement;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Describes the physical seating structure of a bus.
 *
 * A bus can have 1 deck (seater / regular) or 2 decks (sleeper = upper + lower).
 * Admin configures this when adding a bus.
 *
 * ─── How column arrangement works ────────────────────────────────────────────
 *
 *  LayoutArrangement.TWO_TWO   →  [ W  A ] [ A  W ]        (4 seats/row)
 *  LayoutArrangement.TWO_THREE →  [ W  A ] [ A  M  W ]     (5 seats/row)
 *  LayoutArrangement.TWO_ONE  →  [ W  A ] [ W ]            (3 seats/row, luxury)
 *  LayoutArrangement.ONE_ONE  →  [ W ] [ W ]               (2 seats/row, premium)
 *
 * For sleeper buses each berth position maps to UPPER or LOWER deck within
 * the same row concept, configured via deckType on each Seat.
 *
 * ─── Seat generation (done by SeatLayoutService on save) ─────────────────────
 * After admin saves layout config, the service auto-generates Seat records
 * by iterating rows × columns, assigning:
 *   - seatNumber  (sequential, e.g. 1..40)
 *   - rowNumber, columnPosition
 *   - deckType (LOWER/UPPER)
 *   - seatType  (WINDOW / AISLE / MIDDLE) derived from column position + arrangement
 *
 * Admin can then override individual seats (e.g. mark a seat as disabled).
 */
@Entity
@Table(name = "seat_layout")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SeatLayout {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * SINGLE_DECK  = only lower deck (normal seater bus)
     * DOUBLE_DECK  = upper + lower berths (sleeper bus)
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DeckType deckConfiguration;


    /** Column arrangement for the lower deck (or only deck if SINGLE_DECK) */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private LayoutArrangement lowerDeckArrangement;

    /** Number of seat rows in the lower deck */
    @Column(nullable = false)
    private int lowerDeckRows;

    // ─── Upper deck config (used only when deckConfiguration = DOUBLE_DECK) ──

    @Enumerated(EnumType.STRING)
    private LayoutArrangement upperDeckArrangement;   // null if SINGLE_DECK

    private Integer upperDeckRows;                    // null if SINGLE_DECK


    /**
     * Some buses have a full-width rear bench row (e.g. 5-seater last row).
     * Admin can flag this; service will generate a special last row.
     */
    private boolean hasRearBenchRow;

    private Integer rearBenchSeatCount;   // e.g. 5


    /**
     * Auto-generated by SeatLayoutService; persisted so booking service
     * can reference exact seat IDs without re-deriving layout.
     */
    @OneToMany(mappedBy = "seatLayout", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("seatNumber ASC")
    @Builder.Default
    private List<Seat> seats = new ArrayList<>();


    @OneToOne(mappedBy = "seatLayout", fetch = FetchType.LAZY)
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Bus bus;
}