package com.demo.dto;

import com.demo.enums.DeckType;
import com.demo.enums.LayoutArrangement;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SeatLayoutRequest {
 
    DeckType deckConfiguration;         // SINGLE_DECK or DOUBLE_DECK
 
    LayoutArrangement lowerDeckArrangement;
    int lowerDeckRows;
 
    LayoutArrangement upperDeckArrangement;  // null if SINGLE_DECK
    Integer upperDeckRows;                   // null if SINGLE_DECK
 
    boolean hasRearBenchRow;
    Integer rearBenchSeatCount;
 
    /**
     * Optional: admin can pass a pre-built list of seats to override
     * the auto-generated ones (e.g. to disable specific seats or relabel them).
     * If null/empty, seats are fully auto-generated by SeatLayoutService.
     */
    List<SeatOverrideRequest> seatOverrides;
}